### ISSUE TITLE
OpenSCAD 15.3.2 vs. 15.3.3

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.openscad.OpenSCAD#1]
I noticed that the manifest uses version 2015.3.2 instead of 2015.3.3 (cf. http://files.openscad.org/). Is that intentional?

**Comment by MichaelAtOz** [comment]
You mean 2015.03-2 (dash & leading zero), yes that is intentional.
YYYY.MM (without .DD) is a release, YYYY.MM-n is a patch release.
So 2015.03 is the release, then there were three patches,  with 2015.03-3 current.
Patches, usually, are bug fixes without functional change.

There are also Development Snapshots,  YYYY.MM.DD(lately with .<further info>).

**Comment by Alexander-Wilms** [comment]
Ah, alright
